swagger: '2.0'
info:
  version: '1.0.0'
  title: E-corp
  description: api bancaire
  termsOfService: http://
  contact:
    name: Swagger API team
    email: foo@example.com
    url: http://swagger.io
  license:
    name: aucune
    url: http://inexistante
host: userstore.swagger.io
basePath: /
schemes:
  - http
consumes:
  - application/json
  - text/html
produces:
  - application/json
  - text/html
paths:
  /user/{id}:
    get:
      description: information d'un utilisateur

      parameters:
        - name: id
          in: path
          required: true
          description: id du user 
          type: integer
          format: int32
      responses:
        '200':
          description: reponse user
          schema:
            $ref: '#/definitions/user'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/errorModel'
    post:
      description: creer un nouveau user
      operationId: addUser
      parameters:
        - name: id
          in: path
          required: true
          description: user a ajouter
          type: integer
          format: int64
      responses:
        '200':
          description: reponse user
          schema:
            $ref: '#/definitions/user'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/errorModel'
  /compte/{id}:
    get:
      description: information d'un compte utilisateur

      parameters:
        - name: id
          in: path
          required: true
          description: id du compte (Compte courant/ clé primaire)
          type: integer
          format: int32
      responses:
        '200':
          description: reponse compte
          schema:
            $ref: '#/definitions/compte'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/errorModel'
    post:
      description: creer un nouveau compte dans la banque
      operationId: addCompte
      parameters:
        - name: id
          in: path
          required: true
          description: compte a ajouter
          type: integer
          format: int64
      responses:
        '200':
          description: reponse compte
          schema:
            $ref: '#/definitions/compte'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/errorModel'
  /transaction/{id}:
    get:
      description: retourne les transactions effectuées sous ce compte
      operationId: findCompteById
      parameters:
        - name: id
          in: path
          required: true
          description: ID of transaction to fetch
          type: integer
          format: int64
      responses:
        '200':
          description: transaction response
          schema:
            $ref: '#/definitions/transaction'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/errorModel'
    delete:
      description: suprimmer un compte
      operationId: deleteCompte
      parameters:
        - name: id
          in: path
          required: true
          description: ID de la transaction a supprimer
          type: integer
          format: int64
      responses:
        '204':
          description: suppression de la transaction 
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/errorModel'
            
            
            
            
            
            
            
            
            
            
definitions:
  user:
    type: object
    required:
      - id
      - nom
      - typeUser
      - password
    properties:
      id:
        type: integer
        format: int64
      nom:
        type: string
      typeUser:
        type: string
      password:
        type: string
  transaction:
    type: object
    required:
      - id
      - date
      - typeTransaction
      - status
      - noCompteEmetteur
      - noCompteRecepteur
      - message
      - totalPaiement
    properties:
      id:
        type: integer
        format: int64
      date:
        type: string
        format: date
      typeTransaction:
        type: string
      status:
        type: boolean
      noCompteEmetteur:
        type: string
      noCompteRecepteur:
        type: string
      message:
        type: string
      totalPaiement:
        type: number
        format: float
  compte:
    type: object
    required:
      - id
      - name
      - noCompte
      - solde
      - dateCreation
      - transactions
    properties:
      id:
        type: integer
        format: int64
      name:
        type: string
      noCompte:
        type: integer
        format: int64
      solde:
        type: number
        format: float
      dateCreation:
        type: string
        format: date
      transactions:
        type: object
  newCompte:
    type: object
    required:
      - name
    properties:
      id:
        type: integer
        format: int64
      name:
        type: string
      tag:
        type: string
  errorModel:
    type: object
    required:
      - code
      - message
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
