swagger: '2.0'
info:
  version: '1.0.0'
  title: E-corp
  description: api bancaire
  termsOfService: http://
  contact:
    name: Swagger API team
    email: foo@example.com
    url: http://swagger.io
  license:
    name: aucune
    url: http://inexistante
host: userstore.swagger.io
basePath: /
schemes:
  - http
consumes:
  - application/json
  - text/html
produces:
  - application/json
  - text/html
paths:
  /compte:
    get:
      description: information d'un compte utilisateur

      parameters:
        - name: id
          in: query
          description: id du compte (Compte courant/ clé primaire)
          required: true
          type: integer
          format: int32
      responses:
        '200':
          description: reponse compte
          schema:
            $ref: '#/definitions/compte'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/errorModel'
    post:
      description: creer un nouveau compte dans la banque
      operationId: addCompte
      parameters:
        - name: compte
          in: body
          description: compte a ajouter
          required: false
          schema:
            $ref: '#/definitions/compte'
      responses:
        '200':
          description: reponse compte
          schema:
            $ref: '#/definitions/compte'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/errorModel'
  /compte/transactions:
    get:
      description: retourne les transactions effectuées sous ce compte
      operationId: findCompteById
      parameters:
        - name: id
          in: path
          description: ID of pet to fetch
          required: true
          type: integer
          format: int64
      responses:
        '200':
          description: pet response
          schema:
            $ref: '#/definitions/compte'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/errorModel'
    delete:
      description: suprimmer un compte
      operationId: deleteCompte
      parameters:
        - name: id
          in: path
          description: ID du compte a supprimer
          required: true
          type: integer
          format: int64
      responses:
        '204':
          description: suppression compte
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/errorModel'
definitions:
  compte:
    type: object
    required:
      - id
      - name
      - noCompte
      - solde
      - dateCreation
      - transactions
    properties:
      id:
        type: integer
        format: int64
      name:
        type: string
      noCompte:
        type: integer
        format: int64
      solde:
        type: number
        format: float
      dateCreation:
        type: string
        format: date
      transactions:
        type: object
  newCompte:
    type: object
    required:
      - name
    properties:
      id:
        type: integer
        format: int64
      name:
        type: string
      tag:
        type: string
  errorModel:
    type: object
    required:
      - code
      - message
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
